# Generated by Django 5.0.4 on 2024-04-07 08:53

import api_app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api_app.managers.UserManager()),
            ],
        ),
    ]
