# Generated by Django 5.0.4 on 2024-04-07 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 15, 56, 54, 265697)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default="b'UqVZhz5wbr0='", max_length=15),
        ),
    ]
