# Generated by Django 5.0.4 on 2024-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_user_created_at_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='s2fTeaAVI+E=', max_length=15),
        ),
    ]
