# Generated by Django 5.0.4 on 2024-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='TktGTQdif7k=', max_length=15),
        ),
    ]
