# Generated by Django 5.0.4 on 2024-04-08 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_alter_user_referral_code_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 8, 22, 44, 36, 873862)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='Darg1pVYvb4=', max_length=15),
        ),
    ]
